### ISSUE TITLE
Configure ansys doc-changelog and doc-deploy-changelog actions

### ISSUE THREAD

**Issue by ludovicsteinbach** [ansys/grantami-bomanalytics-openapi#128]
See https://actions.docs.ansys.com/version/stable/migrations/index.html#version-v6 for details

**Comment by Andy-Grigg** [comment]
This may be difficult given that these actions hard-code the relevant labels. We use different labels in this repo for the template and API definition updates, which would be grouped into a single 'misc' heading if we use these actions.

We should consider if making this change makes sense.

**Comment by Andy-Grigg** [comment]
I think we should opt out of these changes for auto-generated packages in general. The changes will only ever be "updated to latest swagger.json" or "updated to latest template", which aren't particularly useful. No real functionality will ever be delivered in these packages.
