### ISSUE TITLE
Configure CI to correctly set isRelease

### ISSUE THREAD

**Issue by ludovicsteinbach** [ansys/grantami-bomanalytics-openapi#88]
See https://github.com/ansys/grantami-serverapi-openapi/pull/122 and https://github.com/ansys/grantami-serverapi-openapi/pull/124
Also add the docs url

**Comment by Andy-Grigg** [comment]
Also, assuming https://github.com/ansys/grantami-serverapi-openapi/pull/125 is merged, something similar should be done here as well.
